### ISSUE TITLE
add a reset cart button

### ISSUE THREAD

**Issue by cayeborreo** [cayeborreo/2020-budget#12]
- Bottom part of `shop.js`
- All cart items will be reset to `0`

**Comment by alexyiangou** [comment]
Hey there! I can handle this! :slightly_smiling_face:

**Comment by cayeborreo** [comment]
@alexyiangou Sure thing! Just recently added added the `Wait, I need a reset` button at the bottom of `shop.js`- give it a shot :)

**Comment by cayeborreo** [comment]
Hi @alexyiangou! Tomorrow I'll be attending a Hacktoberfest session to introduce this project. It's happening at 12:30PM Manila time, and all issues will be open for taking :) Just giving you a heads-up in case someone else gets this issue!

**Comment by alexyiangou** [comment]
Sure, thanks for the heads up! I just found free time and I will be done in a while :slightly_smiling_face:
