### ISSUE TITLE
change card appearance if item's price exceeds wallet amount

### ISSUE THREAD

**Issue by cayeborreo** [cayeborreo/2020-budget#21]
## Current behavior
- Only distinguishable feature is input === disabled
![image](https://user-images.githubusercontent.com/39559163/66504168-2cc04600-eafb-11e9-9fca-66eb2f0360f8.png)

### If item's price > state.wallet
- Add className `has-background-light` to `.card-content` and `.card-footer`
- Add className `has-text-danger` to `.subtitle`
![image](https://user-images.githubusercontent.com/39559163/66503952-c89d8200-eafa-11e9-9d42-e3bf4e515867.png)

**Comment by vk239qp** [comment]
Hello, can I have this issue?

**Comment by cayeborreo** [comment]
> Hello, can I have this issue?

Sure! If anything, I would suggest using [classnames](https://github.com/JedWatson/classnames), but you can go ahead and try what floats your boat :)

**Comment by cayeborreo** [comment]
Hi @vk239qp! Tomorrow I'll be attending a Hacktoberfest session to introduce this project. It's happening at 12:30PM Manila time, and all issues will be open for taking :) Just giving you a heads-up in case someone else gets this issue!
