### ISSUE TITLE
format quantity in cart as xx,xxx,xxx (use formatNumber from utils)

### ISSUE THREAD

**Issue by cayeborreo** [cayeborreo/2020-budget#32]
## Current behavior
![screenshot (1)](https://user-images.githubusercontent.com/39559163/66697405-e8ee5c00-ed07-11e9-800e-41233ac26799.png)

## Expected behavior
![screenshot](https://user-images.githubusercontent.com/39559163/66697408-ef7cd380-ed07-11e9-801e-f7f192bfa700.png)

**Comment by objNameGit** [comment]
Can i take this task?
